### ISSUE TITLE
Server stopped when i tried reload http://localhost:8000

### ISSUE THREAD

**Issue by mhaqqiw** [NetrisTV/ws-scrcpy#88]

**Comment by drauggres** [comment]
Did it print a stack trace into the console?

**Comment by mhaqqiw** [comment]
Yes, display this error
```
/Users/test/Repo/ws-scrcpy/dist/server/index.js:1
(function (exports, require, module, __filename, __dirname) { !function(e){var t={};function r(n){if(t[n])return t[n].exports;var i=t[n]={i:n,l:!1,exports:{}};return e[n].call(i.exports,i,i.exports,r),i.l=!0,i.exports}r.m=e,r.c=t,r.d=function(e,t,n){r.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:n})},r.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},r.t=function(e,t){if(1&t&&(e=r(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var n=Object.create(null);if(r.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var i in e)r.d(n,i,function(t){return e[t]}.bind(null,i));return n},r.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(t,"a",t),t},r.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},r.p="

TypeError: this.emitter.off is not a function
    at t.e.off (/Users/test/Repo/ws-scrcpy/dist/server/index.js:1:8272)
    at t.release (/Users/test/Repo/ws-scrcpy/dist/server/index.js:1:33385)
    at t.e.onSocketClose (/Users/test/Repo/ws-scrcpy/dist/server/index.js:1:2032)
    at WebSocket.onClose (/Users/test/Repo/ws-scrcpy/node_modules/ws/lib/event-target.js:129:16)
    at emitTwo (events.js:131:20)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.emitClose (/Users/test/Repo/ws-scrcpy/node_modules/ws/lib/websocket.js:191:10)
    at Socket.socketOnClose (/Users/test/Repo/ws-scrcpy/node_modules/ws/lib/websocket.js:858:15)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:561:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ws-scrcpy@0.7.1-dev start: `cd server && node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ws-scrcpy@0.7.1-dev start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/test/.npm/_logs/2021-04-21T03_25_43_365Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ws-scrcpy@0.7.1-dev start:dist: `cd dist && npm start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ws-scrcpy@0.7.1-dev start:dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/test/.npm/_logs/2021-04-21T03_25_43_417Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ws-scrcpy@0.7.1-dev start: `npm run dist && npm run start:dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ws-scrcpy@0.7.1-dev start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/test/.npm/_logs/2021-04-21T03_25_43_466Z-debug.log
```

**Comment by drauggres** [comment]
What version ot the node are you using?

> TypeError: this.emitter.off is not a function

`emitter.off(eventName, listener)` was added in v10.0.0: [doc](https://nodejs.org/dist/latest-v14.x/docs/api/events.html#events_emitter_off_eventname_listener)

**Comment by mhaqqiw** [comment]
im using node version `v8.15.1`. 
should i change to `v10.0.0`?

**Comment by drauggres** [comment]
You should update to a newer version, not necessary v10.
`v8.x` is already not supported and `v10.x` is about to reach EOL (https://nodejs.org/en/about/releases/).

If you really need this specific old version you can try to change `off` to `removeListener` here:
https://github.com/NetrisTV/ws-scrcpy/blob/63c3cfd4cb32bf6544a7ed670c11b8ab4a2f3054/src/app/TypedEmitter.ts#L25

But I can't guarantee that there is no other incompatibilities.

**Comment by mhaqqiw** [comment]
All working fine after update node to v14. thanks
